// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWDLDd-xhls8Litw56zlgcAv79w0yW0hE',
    appId: '1:837571622040:android:6311dc177e8dca1e5d8ced',
    messagingSenderId: '837571622040',
    projectId: 'quiz-maker-000',
    storageBucket: 'quiz-maker-000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB--MhZOYvGQHTal2USCM9xsTroMUe-PH8',
    appId: '1:837571622040:ios:60434aa223eb05645d8ced',
    messagingSenderId: '837571622040',
    projectId: 'quiz-maker-000',
    storageBucket: 'quiz-maker-000.appspot.com',
    androidClientId: '837571622040-a1es755hjam5u8hnca2icpdtumv64q8d.apps.googleusercontent.com',
    iosClientId: '837571622040-2b0sujj1kn5kg5jpqjsh2ot9i4pqtch7.apps.googleusercontent.com',
    iosBundleId: 'com.plutoapps.quiz-maker',
  );
}
